### ISSUE TITLE
Merge capabilities of the different Range bindings

### ISSUE THREAD

**Issue by deinspanjer** [lightoze/jOOQ-extras-postgresql#3]
My bindings use different names.  I mapped them close to the SQLDataType constants.
I think there might be a couple I have that you don't, at least one is a custom type, so it can probably be excluded.
The biggest thing I see wanting to bring over from my implementation is that I supported all combinations of range inclusive/exclusive specifiers.

AbstractPostgresRangeBinding
PostgresDateRangeBinding
PostgresInt4RangeBinding
PostgresInt8RangeBinding
PostgresNumRangeBinding
PostgresTimeTzRangeBinding
PostgresTsRangeBinding
PostgresTsTzRangeBinding

**Comment by lightoze** [comment]
Probably PostgresTimeTzRangeBinding is a custom type you're talking about?
What about inclusive/exclusive specifiers? Did I miss something in my current implementation?

**Comment by lightoze** [comment]
Also about naming conventions - I used mapped Java types because it's pretty obvious that `Range<Instant>` should be mapped as tstzrange, but not the opposite. E.g. someone might want to use `Range<OffsetDateTime>` or `Range<Byte>` for int4range (for specific data set). Yet I'm not 100% sure and this still can be changed if you have better reasoning.

**Comment by deinspanjer** [comment]
D'oh.  I think I was remembering the test code for the range, in which I saw a construction using [ and ) similar to some of the other sample code.  Looking at your abstract range class, I see that you clearly did implement both specifiers.  I need to look again to see if there is anything at all to be added from my code. There very well might not be.

I'm swamped with a couple of work deadlines at the moment, but when things settle down a bit, I'm looking forward to digging into this more.
